# Generated by Django 4.0.6 on 2023-08-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_started', '0002_survey_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='budget',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='companySize',
            field=models.CharField(default='micro', max_length=100),
            preserve_default=False,
        ),
    ]
